### ISSUE TITLE
Data collection script

### ISSUE THREAD

**Issue by ebimor** [gkahn13/badgr#6]
Hi, thank you for sharing the code and instructions. Is the script to collect/generate the dataset on the robot included in the repo? I mean the script to generate *.tfrecord files. I couldn't find anything about it in the repo.

Cheers,
Ebrahim

**Comment by gkahn13** [comment]
Sorry I didn't include it because the raw dataset (which is used to create the tfrecords) is monstrous (many terabytes). If you read the tfrecords and take a look at the structure, you should be able to figure out the formats the training code needs.

(You also don't have to train with tfrecords, you can use whatever is best for you. I used tfrecords because they are fast.)
